name: Bug Report (Form)
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "browser"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details (Optional)
      description: How can we get in touch with you if we need more info (Email, Discord, etc.)?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? What are the steps to reproduce the problem?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you using/running?
      placeholder: ex. v1.2.0b
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: What platform version are you using (Windows, Mac, Linux, Android, etc.)?
      placeholder: ex. Ubuntu 22.04
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Mobile
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (Optional)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
