name: Feature Request (Form)
description: Suggest an idea to improve the projec
title: "[Feature]: "
labels: ["feature", "browser"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details (Optional)
      description: How can we get in touch with you if we need more info (Email, Discord, etc.)?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen and how it would benefit the project.
      placeholder: Tell us what you would like!
    validations:
      required: true
